//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayEmFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DebitCardDetail
    {
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string NameOnDebitCard { get; set; }

        [Required(ErrorMessage = "Please enter your phone number.")]
        [Display(Name = "Phone Number")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Phone Number.")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter Debit card Number.")]
        [Display(Name = "Debit Card Number")]
        [RegularExpression(@"^([0-9]{16})$", ErrorMessage = "Please enter valid debit card number.")]
        public string DebitCardNumber { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidUpto { get; set; }

        [Required(ErrorMessage = "Please enter the security code.")]
        [Display(Name = "Security Code")]
        public string CVV { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Please enter amount.")]
        [Display(Name = "Amount")]
        [RegularExpression(@"^([0-9]*)$", ErrorMessage = "Invalid amount.")]
        public double Amount { get; set; }

        public virtual Customer Customer { get; set; }
    }
}
