//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayEmFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MobileCompany
    {
        public string CustomerName { get; set; }
        [Required(ErrorMessage = "Please enter phone number.")]
        [Display(Name = "Phone Number")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Phone Number.")]
        public string PhoneNumber { get; set; }
        public string ProviderName { get; set; }
        public string Balance { get; set; }
        [Required(ErrorMessage = "Please enter amount.")]
        [Display(Name = "Amount")]
        [RegularExpression(@"^([0-9]*)$", ErrorMessage = "Invalid amount.")]
        public double Amount { get; set; }
    }
}
